[platformio]
src_dir = .
default_envs = cyd_mini_usb


[env]
platform = espressif32
;platform = espressif32@6.5.0

board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_flags =
	-D USER_SETUP_LOADED
	-D ILI9341_2_DRIVER # 2.4" TFT with ILI9341 driver
;    -D ILI9341_DRIVER  # 2.2" TFT with ILI9341 driver
;	-D USE_HSPI_PORT # Use HSPI (VSPI is default)
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=4
    -D TFT_BL=21

    -D TOUCH_CS=33
    -D TOUCH_IRQ=36

    -D SPI_FREQUENCY=40000000

    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D LOAD_GFXFF


lib_deps =
    bodmer/TFT_eSPI
    knolleary/PubSubClient
    https://github.com/Bodmer/TFT_eSPI.git

[env:cyd_mini_usb]
build_flags =
	${env.build_flags}
	-DTFT_INVERSION_OFF

[env:cyd2_usbC]
build_flags =
	${env.build_flags}
	-DTFT_INVERSION_ON
